id: 898afe05-61af-4726-818b-897d9dead036
version: 34
vcShouldKeepItemLegacyProdMachine: false
name: test_playbook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b3192777-4fd2-4997-89f9-6fe319540600
    type: start
    task:
      id: b3192777-4fd2-4997-89f9-6fe319540600
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: ac2f31f5-6e2a-4392-8b4d-1a4633b20f89
    type: regular
    task:
      id: ac2f31f5-6e2a-4392-8b4d-1a4633b20f89
      version: -1
      name: google-drive-file-permission-create
      description: Creates a permission for a file or shared drive.
      script: GoogleDrive|||google-drive-file-permission-create
      type: regular
      iscommand: true
      brand: GoogleDrive
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      email_address:
        simple: ${testData.emailAddress}
      file_id:
        simple: ${testData.googleDriveFileId}
      type:
        simple: user
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 61b1f3a5-8268-43ba-82a4-ed07d4ab99f4
    type: regular
    task:
      id: 61b1f3a5-8268-43ba-82a4-ed07d4ab99f4
      version: -1
      name: google-drive-file-permissions-list
      description: Lists a file's or shared drive's permissions.
      script: GoogleDrive|||google-drive-file-permissions-list
      type: regular
      iscommand: true
      brand: GoogleDrive
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      file_id:
        simple: ${testData.googleDriveFileId}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 80088f60-1cec-4d82-841f-cb08f09a34a1
    type: regular
    task:
      id: 80088f60-1cec-4d82-841f-cb08f09a34a1
      version: -1
      name: google-drive-file-permission-update
      description: Updates a permission with patch semantics.
      script: GoogleDrive|||google-drive-file-permission-update
      type: regular
      iscommand: true
      brand: GoogleDrive
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      file_id:
        simple: ${testData.googleDriveFileId}
      permission_id:
        simple: ${testData.googleDrivePermissionId}
      role:
        simple: commenter
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: d445a732-d8ef-4418-8edf-31ff29231cf8
    type: regular
    task:
      id: d445a732-d8ef-4418-8edf-31ff29231cf8
      version: -1
      name: google-drive-file-permission-delete
      description: Delete a permission.
      script: GoogleDrive|||google-drive-file-permission-delete
      type: regular
      iscommand: true
      brand: GoogleDrive
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      file_id:
        simple: ${testData.googleDriveFileId}
      permission_id:
        simple: ${testData.googleDrivePermissionId}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 85d5b65b-7d74-411f-89cb-5520936f3aa1
    type: regular
    task:
      id: 85d5b65b-7d74-411f-89cb-5520936f3aa1
      version: -1
      name: google-drive-file-permissions-list
      description: Lists a file's or shared drive's permissions.
      script: GoogleDrive|||google-drive-file-permissions-list
      type: regular
      iscommand: true
      brand: GoogleDrive
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      file_id:
        simple: ${testData.googleDriveFileId}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: e8865268-d5ce-4556-8c52-b1b016ea11eb
    type: title
    task:
      id: e8865268-d5ce-4556-8c52-b1b016ea11eb
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: ce3c745a-5228-45ca-88ba-a3dfb6c3af6d
    type: condition
    task:
      id: ce3c745a-5228-45ca-88ba-a3dfb6c3af6d
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "19"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: GoogleDrive.FilePermission.id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 55a28b93-d264-403e-844d-46288585321a
    type: regular
    task:
      id: 55a28b93-d264-403e-844d-46288585321a
      version: -1
      name: google-drive-file-permissions-list
      description: Lists a file's or shared drive's permissions.
      script: GoogleDrive|||google-drive-file-permissions-list
      type: regular
      iscommand: true
      brand: GoogleDrive
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      file_id:
        simple: ${testData.googleDriveFileId}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 1b4be427-5f64-4027-8a63-15f5e6c183eb
    type: regular
    task:
      id: 1b4be427-5f64-4027-8a63-15f5e6c183eb
      version: -1
      name: google-drive-file-permissions-list
      description: Lists a file's or shared drive's permissions.
      script: GoogleDrive|||google-drive-file-permissions-list
      type: regular
      iscommand: true
      brand: GoogleDrive
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      file_id:
        simple: ${testData.googleDriveFileId}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 73a04d88-1023-460a-806f-1dcb32afd85c
    type: regular
    task:
      id: 73a04d88-1023-460a-806f-1dcb32afd85c
      version: -1
      name: FileCreateAndUpload
      description: |
        Will create a file (using the given data input or entry ID) and upload it to current investigation war room.
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      data:
        simple: Hello World
      filename:
        simple: HelloWorld
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: e79f71bd-d636-486c-85a8-28e19743d9a7
    type: regular
    task:
      id: e79f71bd-d636-486c-85a8-28e19743d9a7
      version: -1
      name: google-drive-file-upload
      description: Creates a new file.
      script: GoogleDrive|||google-drive-file-upload
      type: regular
      iscommand: true
      brand: GoogleDrive
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      entry_id:
        simple: ${File.EntryID}
      file_name:
        simple: ${File.Name}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: 9044844d-408c-4b87-8977-72703ac5c3ba
    type: regular
    task:
      id: 9044844d-408c-4b87-8977-72703ac5c3ba
      version: -1
      name: Set
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: testData.emailAddress
      value:
        simple: tkatzir@paloaltonetworks.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: aa67c049-2b58-421b-82bc-0831ec269323
    type: regular
    task:
      id: aa67c049-2b58-421b-82bc-0831ec269323
      version: -1
      name: google-drive-file-delete
      description: Permanently deletes a file owned by the user without moving it
        to the trash. If the file belongs to a shared drive the user must be an organizer
        on the parent. If the target is a folder, all descendants owned by the user
        are also deleted.
      script: GoogleDrive|||google-drive-file-delete
      type: regular
      iscommand: true
      brand: GoogleDrive
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      file_id:
        simple: ${testData.googleDriveFileId}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: 531282cb-7f41-4bae-85d1-9118dfb49b1b
    type: regular
    task:
      id: 531282cb-7f41-4bae-85d1-9118dfb49b1b
      version: -1
      name: google-drive-files-list
      description: Lists the user's shared drives.
      script: GoogleDrive|||google-drive-files-list
      type: regular
      iscommand: true
      brand: GoogleDrive
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: a6823731-cc94-49e1-8c7b-50ddeb853b4d
    type: regular
    task:
      id: a6823731-cc94-49e1-8c7b-50ddeb853b4d
      version: -1
      name: Set
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: testData.googleDrivePermissionId
      value:
        complex:
          root: GoogleDrive.FilePermission
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: GoogleDrive.FilePermission.emailAddress
                iscontext: true
              right:
                value:
                  simple: ${testData.emailAddress}
          accessor: id
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: 0d183ef1-b05c-40ca-8a3c-7ae8cae506af
    type: regular
    task:
      id: 0d183ef1-b05c-40ca-8a3c-7ae8cae506af
      version: -1
      name: Set
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: testData.googleDriveFileId
      value:
        simple: ${GoogleDrive.File.id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2835,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
