id: playbook-test-rsa-encryption-decryption
version: -1
name: playbook-test-rsa-encryption-decryption
description: Test playbook for Encryption Tools pack.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 15c7bdaa-f7fa-4565-8b4d-64e76289e220
    type: start
    task:
      id: 15c7bdaa-f7fa-4565-8b4d-64e76289e220
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: ec476c0d-7218-44b4-8974-ca4e0afb1d90
    type: regular
    task:
      id: ec476c0d-7218-44b4-8974-ca4e0afb1d90
      version: -1
      name: Encrypt Text
      description: Encrypt text.
      script: '|||rsa-encryption-tools-encrypt-text'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      text_to_encrypt:
        simple: XSOAR
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 2fcda5bf-811f-439a-8657-b06657ac466f
    type: regular
    task:
      id: 2fcda5bf-811f-439a-8657-b06657ac466f
      version: -1
      name: Decrypt Text
      description: Decrypt text.
      script: '|||rsa-encryption-tools-decrypt-text'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      base64_to_decrypt:
        simple: ${EncryptionTools.Value}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: b99de020-05f4-4867-8783-09248c4a03aa
    type: regular
    task:
      id: b99de020-05f4-4867-8783-09248c4a03aa
      version: -1
      name: Decrypted Value to Context
      description: "Takes the comments of a given entry ID and stores them in the\
        \ incident context, under a provided context key. \nFor accessing the last\
        \ executed task's comments, provide ${lastCompletedTaskEntries.[0]} as the\
        \ value for the entryId input parameter."
      scriptName: commentsToContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      contextKey:
        simple: TestText.decrypted
      entryId:
        complex:
          root: ${lastCompletedTaskEntries}
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 449aed3e-9044-450b-8973-79544e9c9549
    type: condition
    task:
      id: 449aed3e-9044-450b-8973-79544e9c9549
      version: -1
      name: Verify Text
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${TestText.decrypted}
            iscontext: true
          right:
            value:
              simple: XSOAR
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 80963e0b-a35b-47c7-8e7b-77d7cf7ca658
    type: title
    task:
      id: 80963e0b-a35b-47c7-8e7b-77d7cf7ca658
      version: -1
      name: File Testing
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: fe2d0bca-644d-4df6-8289-98a86671c2ad
    type: title
    task:
      id: fe2d0bca-644d-4df6-8289-98a86671c2ad
      version: -1
      name: Text Testing
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: c7754449-dd69-4600-8a24-be0f23f56d7f
    type: regular
    task:
      id: c7754449-dd69-4600-8a24-be0f23f56d7f
      version: -1
      name: FileCreateAndUpload
      description: |
        Will create a file (using the given data input or entry ID) and upload it to current investigation war room.
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      data:
        simple: XSOAR encryption tools testing
      filename:
        simple: for_testing.txt
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1185
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 2fd32c3f-1400-4130-8395-119d99b6b1b1
    type: regular
    task:
      id: 2fd32c3f-1400-4130-8395-119d99b6b1b1
      version: -1
      name: Encrypt File
      description: Encrypt file.
      script: '|||rsa-encryption-tools-encrypt-file'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      entry_id:
        simple: '${.=(val.File instanceof Array ? val.File[val.File.length-1].EntryID
          : val.File.EntryID)}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 5a485384-9b21-4e95-8c36-5af9a0183c81
    type: regular
    task:
      id: 5a485384-9b21-4e95-8c36-5af9a0183c81
      version: -1
      name: Decrypt File
      description: Decrypt file.
      script: '|||rsa-encryption-tools-decrypt-file'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      entry_id:
        simple: '${.=(val.InfoFile instanceof Array ? val.InfoFile[val.InfoFile.length-1].EntryID
          : val.InfoFile.EntryID)}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1535
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: f2b3b45b-7350-4c89-8d58-4bb2e5fc333a
    type: condition
    task:
      id: f2b3b45b-7350-4c89-8d58-4bb2e5fc333a
      version: -1
      name: Verify File Content
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: FileData
            iscontext: true
          right:
            value:
              simple: XSOAR encryption tools testing
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1885
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 0fcf99b8-74b7-40fc-8f36-8e605c7c9ed4
    type: regular
    task:
      id: 0fcf99b8-74b7-40fc-8f36-8e605c7c9ed4
      version: -1
      name: ReadFile
      description: Load the contents of a file into context.
      scriptName: ReadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      entryID:
        simple: '${.=(val.InfoFile instanceof Array ? val.InfoFile[val.InfoFile.length-1].EntryID
          : val.InfoFile.EntryID)}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1710
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: 17aa3ee7-431e-45ff-88e4-d739cecdc323
    type: title
    task:
      id: 17aa3ee7-431e-45ff-88e4-d739cecdc323
      version: -1
      name: Test Exports
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "17"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2060
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: ccba8d55-d9d8-4224-8bf1-a6e190b566b1
    type: regular
    task:
      id: ccba8d55-d9d8-4224-8bf1-a6e190b566b1
      version: -1
      name: Export Public Key
      description: Exports the public key to a file.
      script: '|||rsa-encryption-tools-export-public-key'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      output_file_name:
        simple: public.key
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2205
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "18":
    id: "18"
    taskid: 50f7fba6-8dab-4055-88c0-6bc8d3cae1ca
    type: condition
    task:
      id: 50f7fba6-8dab-4055-88c0-6bc8d3cae1ca
      version: -1
      name: Verify exported files
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "19"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: InfoFile.Name
            iscontext: true
          right:
            value:
              simple: public.key
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "19":
    id: "19"
    taskid: f85aa5f7-adba-47f5-8f11-6d9069222224
    type: title
    task:
      id: f85aa5f7-adba-47f5-8f11-6d9069222224
      version: -1
      name: DONE
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2555
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2570,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 6.0.0
