id: FireEyeNX-Test
version: -1
name: FireEyeNX-Test
description: This playbook uses the FireEye NX integration and tests the scenarios
  of the various commands like fireeye-nx-get-artifacts-metadata-by-alert, fireeye-nx-get-alert-details,
  fireeye-nx-get-reports, fireeye-nx-get-alerts, fireeye-nx-get-artifacts-by-alert
  and fireeye-nx-get-events.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: bac6f935-59f4-4686-8ca8-d78db0382c8c
    type: start
    task:
      id: bac6f935-59f4-4686-8ca8-d78db0382c8c
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: da17aa66-4ba8-49e3-896a-53005bcb640b
    type: regular
    task:
      id: da17aa66-4ba8-49e3-896a-53005bcb640b
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 64d45344-ad65-4e92-800c-442f8d711824
    type: regular
    task:
      id: 64d45344-ad65-4e92-800c-442f8d711824
      version: -1
      name: fireeye-nx-get-artifacts-metadata-by-alert
      script: '|||fireeye-nx-get-artifacts-metadata-by-alert'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      uuid:
        simple: ${FireEyeNX.Alert.Uuid}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 62b9c161-2e9b-46fa-83d0-b2e9367f6232
    type: condition
    task:
      id: 62b9c161-2e9b-46fa-83d0-b2e9367f6232
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.Uuid
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.ArtifactsMetadata.ArtifactType
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.ArtifactsMetadata.ArtifactName
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.ArtifactsMetadata.ArtifactSize
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: b40ea12b-6102-4ad1-89aa-7dbeaacba6fb
    type: regular
    task:
      id: b40ea12b-6102-4ad1-89aa-7dbeaacba6fb
      version: -1
      name: fireeye-nx-get-reports
      script: '|||fireeye-nx-get-reports'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      end_time:
        simple: 2020-02-29T23:59:59
      report_type:
        simple: IPS Executive Summary Report
      start_time:
        simple: 2020-01-29T23:59:59
      time_frame:
        simple: between
      type:
        simple: csv
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 31a74435-a1ea-4d82-8bb3-acf6335cbea9
    type: condition
    task:
      id: 31a74435-a1ea-4d82-8bb3-acf6335cbea9
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: InfoFile.Name
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: InfoFile.EntryID
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: InfoFile.Size
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: InfoFile.Type
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: InfoFile.Info
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 962eec23-135b-47c5-8448-6f7276d01824
    type: title
    task:
      id: 962eec23-135b-47c5-8448-6f7276d01824
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 2ddf1bae-5998-4be6-8da4-cd13ea6854be
    type: regular
    task:
      id: 2ddf1bae-5998-4be6-8da4-cd13ea6854be
      version: -1
      name: fireeye-nx-get-artifacts-by-alert
      description: Downloads malware artifacts data for the specified UUID as a zip
        file.
      script: '|||fireeye-nx-get-artifacts-by-alert'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      uuid:
        simple: ${FireEyeNX.Alert.Uuid}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 77ed0b8c-d261-42a8-81a6-a49bdc6b17fc
    type: condition
    task:
      id: 77ed0b8c-d261-42a8-81a6-a49bdc6b17fc
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: File
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: File.Name
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: File.Extension
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: File.Type
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: File.Size
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: File.Info
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: File.MD5
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: File.SHA1
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: File.SHA256
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: File.SSDeep
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: File.EntryID
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 395d4a96-23e5-418e-8c9b-b17bc0f43c78
    type: regular
    task:
      id: 395d4a96-23e5-418e-8c9b-b17bc0f43c78
      version: -1
      name: fireeye-nx-get-events
      description: Search and Retrieve FireEye events based on several filters.
      script: '|||fireeye-nx-get-events'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      duration:
        simple: 48_hours
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: acfa359f-01e1-4f74-8f4d-7a0333160897
    type: regular
    task:
      id: acfa359f-01e1-4f74-8f4d-7a0333160897
      version: -1
      name: fireeye-nx-get-alerts
      description: Search and Retrieve FireEye alerts based on several filters.
      script: '|||fireeye-nx-get-alerts'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      alert_id:
        simple: "36076"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 3a659f6c-89cf-4d71-801e-4d02e68ad9c5
    type: condition
    task:
      id: 3a659f6c-89cf-4d71-801e-4d02e68ad9c5
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.Src.Ip
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.Src.Port
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.AlertUrl
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.Action
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.Occurred
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.AttackTime
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.ApplianceId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.Id
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.Name
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.Severity
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.Uuid
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.Ack
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.Product
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.Vlan
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.Malicious
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Alert.ScVersion
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 535
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: 119f71d9-9a3e-42d6-8226-c4401931bc59
    type: condition
    task:
      id: 119f71d9-9a3e-42d6-8226-c4401931bc59
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.EventId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.Occurred
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.SrcIp
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.DstIp
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.DstPort
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.Severity
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.SignatureRev
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.SignatureIden
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.SignatureMatchCnt
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.Vlan
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.SrcMac
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.DstMac
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.RuleName
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.SensorId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.ActionTaken
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.AttackMode
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.InterfaceId
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: FireEyeNX.Event.Protocol
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2125
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2170,
        "width": 390,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0

