id: db2e16c3-ef1e-4b4f-8f1f-489c0fae303e
version: 4
vcShouldKeepItemLegacyProdMachine: false
name: testaaa
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 73a968d7-5511-47fa-87cb-ce3cc38e6a5e
    type: start
    task:
      id: 73a968d7-5511-47fa-87cb-ce3cc38e6a5e
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 28ac16b6-5fbf-48c5-8cc9-25f97f8e28b9
    type: regular
    task:
      id: 28ac16b6-5fbf-48c5-8cc9-25f97f8e28b9
      version: -1
      name: aaa-get
      description: Retrieves all blocked senders, URLs, and SHA-1 hash values that
        have been configured to quarantine Exchange Online email messages.
      script: TrendMicro Cloud App Security|||trendmicro-cas-blocked-lists-get
      type: regular
      iscommand: true
      brand: aaa
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 255,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
