id: search_and_delete_emails_-_generic
version: -1
contentitemexportablefields:
  contentitemfields: {}
name: Search And Delete Emails - Generic
description: This playbook searches and delete emails with similar attributes of a
  malicious email.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 808e9cce-8112-49d4-8624-907a6fbeb394
    type: start
    task:
      id: 808e9cce-8112-49d4-8624-907a6fbeb394
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: a7b6936c-73ee-4fba-8314-3514fa9a9070
    type: playbook
    task:
      id: a7b6936c-73ee-4fba-8314-3514fa9a9070
      version: -1
      name: Search And Delete Emails - EWS
      description: This playbook searches EWS to identify and delete emails with similar
        attributes of a malicious email.
      playbookName: Search And Delete Emails - EWS
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      AttachmentName:
        complex:
          root: inputs.AttachmentName
      DeleteType:
        simple: trash
      From:
        complex:
          root: inputs.From
      Limit:
        simple: "20"
      SearchThisWeek:
        simple: "true"
      Subject:
        complex:
          root: inputs.Subject
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 340,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
  "2":
    id: "2"
    taskid: 88c58e53-8fe7-4ca2-8697-0ed3f67191fe
    type: title
    task:
      id: 88c58e53-8fe7-4ca2-8697-0ed3f67191fe
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 70,
          "y": 1240
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 5902bdde-4d32-4ee2-8cb3-73707f7c90aa
    type: playbook
    task:
      id: 5902bdde-4d32-4ee2-8cb3-73707f7c90aa
      version: -1
      name: O365 - Security And Compliance - Search And Delete
      description: |-
        This playbook performs the following steps:
        1. Creates a compliance search.
        2. Starts a compliance search.
        3. Waits for the compliance search to complete.
        4. Gets the results of the compliance search.
        5. Gets the preview results, if specified.
        6. Deletes the search results (Hard/Soft).
      playbookName: O365 - Security And Compliance - Search And Delete
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      allow_not_found_exchange_locations:
        complex:
          root: |
            inputs.O365AllowNotFoundExchangeLocations
      case: {}
      delete_type:
        complex:
          root: inputs.O365DeleteType
      description: {}
      exchange_location:
        complex:
          root: ExchangeLocation
      exchange_location_exclusion:
        complex:
          root: inputs.O365ExchangeLocationExclusion
      force:
        simple: "false"
      kql:
        complex:
          root: inputs.O365KQL
      preview:
        simple: "true"
      search_name: {}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": -200,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
  "4":
    id: "4"
    taskid: dff2957e-59a7-4323-8886-4fd02a5ebdb6
    type: condition
    task:
      id: dff2957e-59a7-4323-8886-4fd02a5ebdb6
      version: -1
      name: In what integration should emails be searched and deleted?
      description: Checks which integration and playbook should be used to run the
        search & delete action, by checking the SearchAndDeleteIntegration playbook
        input.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      EWS:
      - "1"
      O365:
      - "5"
    separatecontext: false
    conditions:
    - label: EWS
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: inputs.SearchAndDeleteIntegration
            iscontext: true
          right:
            value:
              simple: EWS
          ignorecase: true
    - label: O365
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: inputs.SearchAndDeleteIntegration
            iscontext: true
          right:
            value:
              simple: O365
          ignorecase: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: d2db2ba7-3e13-47ce-8fd2-0842b89a386f
    type: condition
    task:
      id: d2db2ba7-3e13-47ce-8fd2-0842b89a386f
      version: -1
      name: From where should emails be searched and deleted?
      description: Checks if a target to search and delete emails from was specified.
        Determined by the O365ExchangeLocation playbook input.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      All Mailboxes:
      - "7"
      Recipient's Mailbox:
      - "8"
    separatecontext: false
    conditions:
    - label: Recipient's Mailbox
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: inputs.O365ExchangeLocation
            iscontext: true
          right:
            value:
              simple: SingleMailbox
          ignorecase: true
    - label: All Mailboxes
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: inputs.O365ExchangeLocation
            iscontext: true
          right:
            value:
              simple: All
          ignorecase: true
    view: |-
      {
        "position": {
          "x": -590,
          "y": 420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 25801150-ef91-4ccc-8275-5ca5225fc857
    type: condition
    task:
      id: 25801150-ef91-4ccc-8275-5ca5225fc857
      version: -1
      name: Manually decide where to search & delete the email
      description: Allows the analyst to decide where to search for and delete the
        email from - is it from the mailbox of the recipient, or from all available
        mailboxes?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      All Mailboxes:
      - "7"
      Recipients Mailbox:
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -590,
          "y": 630
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: ac91c4b3-329f-4341-894e-4cb9a92ab88e
    type: regular
    task:
      id: ac91c4b3-329f-4341-894e-4cb9a92ab88e
      version: -1
      name: Set all mailboxes to be searched
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      append: {}
      key:
        simple: ExchangeLocation
      stringify: {}
      value:
        simple: All
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -910,
          "y": 830
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 586e6f48-4fd2-489d-8948-f5327f2e431d
    type: regular
    task:
      id: 586e6f48-4fd2-489d-8948-f5327f2e431d
      version: -1
      name: Set the "email to" as the mailbox to search
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      append: {}
      key:
        simple: ExchangeLocation
      stringify: {}
      value:
        complex:
          root: inputs.To
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -320,
          "y": 830
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
system: true
view: |-
  {
    "linkLabelsPosition": {
      "4_1_EWS": 0.18
    },
    "paper": {
      "dimensions": {
        "height": 1255,
        "width": 1630,
        "x": -910,
        "y": 50
      }
    }
  }
inputs:
- key: From
  value:
    complex:
      root: incident
      accessor: emailfrom
  required: false
  description: The value of the malicious email's "From" attribute.
  playbookInputQuery:
- key: Subject
  value:
    complex:
      root: incident
      accessor: emailsubject
  required: false
  description: The value of the malicious email's "Subject" attribute.
  playbookInputQuery:
- key: AttachmentName
  value:
    complex:
      root: incident
      accessor: attachmentname
  required: false
  description: The value of the malicious email's "AttachmentName" attribute.
  playbookInputQuery:
- key: SearchAndDeleteIntegration
  value:
    simple: EWS
  required: true
  description: The integration in which to run the search and delete action. Can be
    O365, or EWS.
  playbookInputQuery:
- key: O365ExchangeLocation
  value:
    complex:
      root: incident
      accessor: emailto
  required: false
  description: Used only in O365. Comma-separated list of mailboxes/distribution groups
    to include, or use the value "All" to include all.
  playbookInputQuery:
- key: O365KQL
  value: {}
  required: false
  description: Used only in O365. Text search string or a query that is formatted
    using the Keyword Query Language (KQL).
  playbookInputQuery:
- key: O365Description
  value: {}
  required: false
  description: Used only in O365. Description of the compliance search.
  playbookInputQuery:
- key: |
    O365AllowNotFoundExchangeLocations
  value:
    simple: "false"
  required: false
  description: Used only in O365. Whether to include mailboxes other than regular
    user mailboxes in the compliance search. Default is "false".
  playbookInputQuery:
- key: O365DeleteType
  value:
    simple: inputs.O365DeleteType
  required: false
  description: Used only in O365. The delete type to perform on the search results.
    Possible values are Hard and Soft or leave empty to select manually. (Hard = Unrecoverable,
    Soft=Recoverable)
  playbookInputQuery:
- key: O365ExchangeLocationExclusion
  value:
    complex:
      root: inputs.O365ExchangeLocationExclusion
  required: false
  description: Used only when searching and deleting emails in O365. The exchange
    location. Determines from where to search and delete emails searched using O365
    playbooks. Use the value "All" to search all mailboxes, use "SingleMailbox" to
    search and delete the email only from the recipient's inbox, or specify "Manual"
    to decide manually for every incident. Note - searching all mailboxes may take
    a significant amount of time.
  playbookInputQuery:
- key: To
  value:
    complex:
      root: incident
      accessor: emailto
  required: false
  description: The email address to which the email was sent. This is used if the
    user decides to search for and delete emails only from the inbox of the recipient
    using O365.
  playbookInputQuery:
outputs: []
fromversion: 5.0.0
tests:
- No test
