id: search_and_delete_emails_-_generic
version: 25
contentitemexportablefields:
  contentitemfields:
    packID: CommonPlaybooks
    itemVersion: 1.9.7
    fromServerVersion: ""
    toServerVersion: ""
vcShouldKeepItemLegacyProdMachine: false
name: Search And Delete Emails - Generic
description: This playbook searches and delete emails with similar attributes of a
  malicious email.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 808e9cce-8112-49d4-8624-907a6fbeb394
    type: start
    task:
      id: 808e9cce-8112-49d4-8624-907a6fbeb394
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "1":
    id: "1"
    taskid: a7b6936c-73ee-4fba-8314-3514fa9a9070
    type: playbook
    task:
      id: a7b6936c-73ee-4fba-8314-3514fa9a9070
      version: -1
      name: Search And Delete Emails - EWS
      description: This playbook searches EWS to identify and delete emails with similar
        attributes of a malicious email.
      playbookName: Search And Delete Emails - EWS
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      AttachmentName:
        complex:
          root: inputs.AttachmentName
      DeleteType:
        simple: trash
      From:
        complex:
          root: inputs.From
      Limit:
        simple: "20"
      SearchThisWeek:
        simple: "true"
      Subject:
        complex:
          root: inputs.Subject
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 320,
          "y": 380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
  "2":
    id: "2"
    taskid: 88c58e53-8fe7-4ca2-8697-0ed3f67191fe
    type: title
    task:
      id: 88c58e53-8fe7-4ca2-8697-0ed3f67191fe
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 580
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "3":
    id: "3"
    taskid: e55d43ec-5acc-4a31-8fa0-c3cf37de08f0
    type: playbook
    task:
      id: e55d43ec-5acc-4a31-8fa0-c3cf37de08f0
      version: -1
      name: O365 - Security And Compliance - Search And Delete
      description: |-
        This playbook performs the following steps:
        1. Creates a compliance search.
        2. Starts a compliance search.
        3. Waits for the compliance search to complete.
        4. Gets the results of the compliance search.
        5. Gets the preview results, if specified.
        6. Deletes the search results (Hard/Soft).
      playbookName: O365 - Security And Compliance - Search And Delete
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      allow_not_found_exchange_locations:
        complex:
          root: |
            inputs.O365AllowNotFoundExchangeLocations
      case: {}
      delete_type:
        complex:
          root: inputs.O365DeleteType
      description: {}
      exchange_location:
        complex:
          root: inputs.O365ExchangeLocation
      exchange_location_exclusion:
        complex:
          root: inputs.O365ExchangeLocationExclusion
      force:
        simple: "false"
      kql:
        complex:
          root: inputs.O365KQL
      preview:
        simple: "true"
      search_name: {}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": -240,
          "y": 380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
  "4":
    id: "4"
    taskid: 25c0ad98-1c98-44bc-8741-4a7ee7cfdd9c
    type: condition
    task:
      id: 25c0ad98-1c98-44bc-8741-4a7ee7cfdd9c
      version: -1
      name: Where should emails be searched and deleted?
      description: Checks which integration and playbook should be used to run the
        search & delete action, by checking the SearchAndDeleteIntegration playbook
        input.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      EWS:
      - "1"
      O365:
      - "3"
    separatecontext: false
    conditions:
    - label: EWS
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: inputs.SearchAndDeleteIntegration
            iscontext: true
          right:
            value:
              simple: EWS
          ignorecase: true
    - label: O365
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: inputs.SearchAndDeleteIntegration
            iscontext: true
          right:
            value:
              simple: O365
          ignorecase: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
system: true
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 595,
        "width": 940,
        "x": -240,
        "y": 50
      }
    }
  }
inputs:
- key: From
  value:
    complex:
      root: incident
      accessor: emailfrom
  required: false
  description: The value of the malicious email's "From" attribute.
  playbookInputQuery: null
- key: Subject
  value:
    complex:
      root: incident
      accessor: emailsubject
  required: false
  description: The value of the malicious email's "Subject" attribute.
  playbookInputQuery: null
- key: AttachmentName
  value:
    complex:
      root: incident
      accessor: attachmentname
  required: false
  description: The value of the malicious email's "AttachmentName" attribute.
  playbookInputQuery: null
- key: SearchAndDeleteIntegration
  value:
    simple: EWS
  required: true
  description: The integration in which to run the search and delete action. Can be
    O365, or EWS.
  playbookInputQuery: null
- key: O365ExchangeLocation
  value:
    complex:
      root: incident
      accessor: emailto
  required: false
  description: Used only in O365. Comma-separated list of mailboxes/distribution groups
    to include, or use the value "All" to include all.
  playbookInputQuery: null
- key: O365KQL
  value: {}
  required: false
  description: Used only in O365. Text search string or a query that is formatted
    using the Keyword Query Language (KQL).
  playbookInputQuery: null
- key: O365Description
  value: {}
  required: false
  description: Used only in O365. Description of the compliance search.
  playbookInputQuery: null
- key: |
    O365AllowNotFoundExchangeLocations
  value:
    simple: "false"
  required: false
  description: Used only in O365. Whether to include mailboxes other than regular
    user mailboxes in the compliance search. Default is "false".
  playbookInputQuery: null
- key: O365DeleteType
  value:
    simple: inputs.O365DeleteType
  required: false
  description: Used only in O365. The delete type to perform on the search results.
    Possible values are Hard and Soft or leave empty to select manually. (Hard = Unrecoverable,
    Soft=Recoverable)
  playbookInputQuery: null
- key: O365ExchangeLocationExclusion
  value:
    complex:
      root: inputs.O365ExchangeLocationExclusion
  required: false
  description: Used only in O365. Comma-separated list of mailboxes/distribution groups
    to exclude when you use the value "All" for the exchange_location parameter.
  playbookInputQuery: null
outputs: []
fromversion: 5.0.0
tests:
- No test
