id: playbook-test-encryption-decryption
version: -1
name: playbook-test-encryption-decryption
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e8109a66-5183-437c-8d65-bae99d031abc
    type: start
    task:
      id: e8109a66-5183-437c-8d65-bae99d031abc
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: ef3dcffa-d525-45a3-87f2-1a2fb41aca76
    type: regular
    task:
      id: ef3dcffa-d525-45a3-87f2-1a2fb41aca76
      version: -1
      name: Create Keys with Override
      description: Create new RSA keys.
      script: '|||encryption-tools-create-keys'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      nbits:
        simple: "512"
      override_keys:
        simple: "true"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 6e9ec731-8b14-4103-8b48-3725ab74b99c
    type: regular
    task:
      id: 6e9ec731-8b14-4103-8b48-3725ab74b99c
      version: -1
      name: Encrypt Text
      description: Encrypt text.
      script: '|||encryption-tools-encrypt-text'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      text_to_encrypt:
        simple: XSOAR
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 68fa8740-b12b-451b-8507-40ebdf1f1d46
    type: regular
    task:
      id: 68fa8740-b12b-451b-8507-40ebdf1f1d46
      version: -1
      name: Encrypted Value to Context
      description: "Takes the comments of a given entry ID and stores them in the\
        \ incident context, under a provided context key. \nFor accessing the last\
        \ executed task's comments, provide ${lastCompletedTaskEntries.[0]} as the\
        \ value for the entryId input parameter."
      scriptName: commentsToContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      contextKey:
        simple: TestText.encrypted
      entryId:
        complex:
          root: ${lastCompletedTaskEntries}
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 75a0f26b-e260-4f52-8698-90bb13a58454
    type: regular
    task:
      id: 75a0f26b-e260-4f52-8698-90bb13a58454
      version: -1
      name: Decrypt Text
      description: Decrypt text.
      script: '|||encryption-tools-decrypt-text'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      base64_to_decrypt:
        simple: ${TestText.encrypted}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 1bb768c8-0ba1-4693-8fa0-228d5591732b
    type: regular
    task:
      id: 1bb768c8-0ba1-4693-8fa0-228d5591732b
      version: -1
      name: Decrypted Value to Context
      description: "Takes the comments of a given entry ID and stores them in the\
        \ incident context, under a provided context key. \nFor accessing the last\
        \ executed task's comments, provide ${lastCompletedTaskEntries.[0]} as the\
        \ value for the entryId input parameter."
      scriptName: commentsToContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      contextKey:
        simple: TestText.decrypted
      entryId:
        complex:
          root: ${lastCompletedTaskEntries}
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 5e884c51-151a-4240-8610-d992f51c049a
    type: condition
    task:
      id: 5e884c51-151a-4240-8610-d992f51c049a
      version: -1
      name: Verify Text
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${TestText.decrypted}
            iscontext: true
          right:
            value:
              simple: XSOAR
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1215
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: ec3e79e5-11d8-48b4-8303-3d0cb183e7c1
    type: title
    task:
      id: ec3e79e5-11d8-48b4-8303-3d0cb183e7c1
      version: -1
      name: File Testing
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: d17a0eae-0265-402a-84b5-ad820b27b5df
    type: title
    task:
      id: d17a0eae-0265-402a-84b5-ad820b27b5df
      version: -1
      name: Text Testing
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 6eae44a3-ce4d-405f-87bd-acc1aa317cb0
    type: regular
    task:
      id: 6eae44a3-ce4d-405f-87bd-acc1aa317cb0
      version: -1
      name: FileCreateAndUpload
      description: |
        Will create a file (using the given data input or entry ID) and upload it to current investigation war room.
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      data:
        simple: XSOAR encryption tools testing
      filename:
        simple: for_testing.txt
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1535
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 41ff6b0b-5841-444a-8cc8-74319a7209da
    type: regular
    task:
      id: 41ff6b0b-5841-444a-8cc8-74319a7209da
      version: -1
      name: Encrypt File
      description: Encrypt file.
      script: '|||encryption-tools-encrypt-file'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      entry_id:
        simple: '${.=(val.File instanceof Array ? val.File[val.File.length-1].EntryID
          : val.File.EntryID)}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1710
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 4cbe2580-15f0-4cb5-8fb0-3e8e28a69caa
    type: regular
    task:
      id: 4cbe2580-15f0-4cb5-8fb0-3e8e28a69caa
      version: -1
      name: Decrypt File
      description: Decrypt file.
      script: '|||encryption-tools-decrypt-file'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      entry_id:
        simple: '${.=(val.File instanceof Array ? val.File[val.File.length-1].EntryID
          : val.File.EntryID)}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1885
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 30d3bf8a-c154-40f2-8d39-c02ee73e696f
    type: condition
    task:
      id: 30d3bf8a-c154-40f2-8d39-c02ee73e696f
      version: -1
      name: Verify File Content
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: FileData
            iscontext: true
          right:
            value:
              simple: XSOAR encryption tools testing
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2235
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 798966e8-d045-41d0-8930-435afacc3487
    type: regular
    task:
      id: 798966e8-d045-41d0-8930-435afacc3487
      version: -1
      name: ReadFile
      description: Load the contents of a file into context.
      scriptName: ReadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      entryID:
        simple: '${.=(val.File instanceof Array ? val.File[val.File.length-1].EntryID
          : val.File.EntryID)}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2060
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: e45a6d99-8d2f-4597-8dcf-90e2f3ce2cc1
    type: title
    task:
      id: e45a6d99-8d2f-4597-8dcf-90e2f3ce2cc1
      version: -1
      name: DONE
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2425,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 6.0.0
description: Test playbook for the Encyption Tools integration.
