id: playbook-test-encryption-decryption
version: -1
name: playbook-test-encryption-decryption
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e8109a66-5183-437c-8d65-bae99d031abc
    type: start
    task:
      id: e8109a66-5183-437c-8d65-bae99d031abc
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 7c68adb8-9f13-44dc-8997-3b670f4b4d52
    type: regular
    task:
      id: 7c68adb8-9f13-44dc-8997-3b670f4b4d52
      version: -1
      name: Create Keys with Override
      description: Create new RSA keys.
      script: '|||encryption-tools-create-keys'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      nbits:
        simple: "512"
      override_keys:
        simple: "true"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 6e9ec731-8b14-4103-8b48-3725ab74b99c
    type: regular
    task:
      id: 6e9ec731-8b14-4103-8b48-3725ab74b99c
      version: -1
      name: Encrypt Text
      description: Encrypt text.
      script: '|||encryption-tools-encrypt-text'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      text_to_encrypt:
        simple: XSOAR
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: a0ce222f-4b41-4384-8e02-19efbffa62d1
    type: regular
    task:
      id: a0ce222f-4b41-4384-8e02-19efbffa62d1
      version: -1
      name: Decrypt Text
      description: Decrypt text.
      script: '|||encryption-tools-decrypt-text'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      base64_to_decrypt:
        simple: ${EncryptionTools.Value}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 1bb768c8-0ba1-4693-8fa0-228d5591732b
    type: regular
    task:
      id: 1bb768c8-0ba1-4693-8fa0-228d5591732b
      version: -1
      name: Decrypted Value to Context
      description: "Takes the comments of a given entry ID and stores them in the\
        \ incident context, under a provided context key. \nFor accessing the last\
        \ executed task's comments, provide ${lastCompletedTaskEntries.[0]} as the\
        \ value for the entryId input parameter."
      scriptName: commentsToContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      contextKey:
        simple: TestText.decrypted
      entryId:
        complex:
          root: ${lastCompletedTaskEntries}
          transformers:
          - operator: LastArrayElement
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 5e884c51-151a-4240-8610-d992f51c049a
    type: condition
    task:
      id: 5e884c51-151a-4240-8610-d992f51c049a
      version: -1
      name: Verify Text
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${TestText.decrypted}
            iscontext: true
          right:
            value:
              simple: XSOAR
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: ec3e79e5-11d8-48b4-8303-3d0cb183e7c1
    type: title
    task:
      id: ec3e79e5-11d8-48b4-8303-3d0cb183e7c1
      version: -1
      name: File Testing
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1215
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: d17a0eae-0265-402a-84b5-ad820b27b5df
    type: title
    task:
      id: d17a0eae-0265-402a-84b5-ad820b27b5df
      version: -1
      name: Text Testing
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 6eae44a3-ce4d-405f-87bd-acc1aa317cb0
    type: regular
    task:
      id: 6eae44a3-ce4d-405f-87bd-acc1aa317cb0
      version: -1
      name: FileCreateAndUpload
      description: |
        Will create a file (using the given data input or entry ID) and upload it to current investigation war room.
      scriptName: FileCreateAndUpload
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      data:
        simple: XSOAR encryption tools testing
      filename:
        simple: for_testing.txt
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 41ff6b0b-5841-444a-8cc8-74319a7209da
    type: regular
    task:
      id: 41ff6b0b-5841-444a-8cc8-74319a7209da
      version: -1
      name: Encrypt File
      description: Encrypt file.
      script: '|||encryption-tools-encrypt-file'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      entry_id:
        simple: '${.=(val.File instanceof Array ? val.File[val.File.length-1].EntryID
          : val.File.EntryID)}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1535
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 819fc9ee-df3d-4c5d-855d-5cf2c294aa7f
    type: regular
    task:
      id: 819fc9ee-df3d-4c5d-855d-5cf2c294aa7f
      version: -1
      name: Decrypt File
      description: Decrypt file.
      script: '|||encryption-tools-decrypt-file'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      entry_id:
        simple: '${.=(val.InfoFile instanceof Array ? val.InfoFile[val.InfoFile.length-1].EntryID
          : val.InfoFile.EntryID)}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1710
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 30d3bf8a-c154-40f2-8d39-c02ee73e696f
    type: condition
    task:
      id: 30d3bf8a-c154-40f2-8d39-c02ee73e696f
      version: -1
      name: Verify File Content
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: FileData
            iscontext: true
          right:
            value:
              simple: XSOAR encryption tools testing
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2060
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 3a08b14b-2002-47f9-834a-660c6d7041e0
    type: regular
    task:
      id: 3a08b14b-2002-47f9-834a-660c6d7041e0
      version: -1
      name: ReadFile
      description: Load the contents of a file into context.
      scriptName: ReadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      entryID:
        simple: '${.=(val.InfoFile instanceof Array ? val.InfoFile[val.InfoFile.length-1].EntryID
          : val.InfoFile.EntryID)}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1885
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: fc92850a-b2b5-472b-8497-c981644bfbb0
    type: title
    task:
      id: fc92850a-b2b5-472b-8497-c981644bfbb0
      version: -1
      name: Test Exports
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2235
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: 3031f5f1-f86a-4103-87a9-3b1c1b16f845
    type: regular
    task:
      id: 3031f5f1-f86a-4103-87a9-3b1c1b16f845
      version: -1
      name: Export Private Key
      description: Exports the private key to a file.
      script: '|||encryption-tools-export-private-key'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      output_file_name:
        simple: private_key
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: 756fc21c-c607-4699-818c-dc6bbdad1f44
    type: regular
    task:
      id: 756fc21c-c607-4699-818c-dc6bbdad1f44
      version: -1
      name: Export Public Key
      description: Exports the private key to a file.
      script: '|||encryption-tools-export-private-key'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      output_file_name:
        simple: public_key
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2555
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "18":
    id: "18"
    taskid: 6589face-6034-47c6-8965-184c8e1de2b1
    type: condition
    task:
      id: 6589face-6034-47c6-8965-184c8e1de2b1
      version: -1
      name: Verify exported files
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "19"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: InfoFile.Name
            iscontext: true
          right:
            value:
              simple: private_key
      - - operator: containsGeneral
          left:
            value:
              simple: InfoFile.Name
            iscontext: true
          right:
            value:
              simple: public_key
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "19":
    id: "19"
    taskid: c729eaf4-b6c7-4112-87c3-bee283896d2f
    type: title
    task:
      id: c729eaf4-b6c7-4112-87c3-bee283896d2f
      version: -1
      name: DONE
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2905
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2920,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 6.0.0
description: Test playbook for Encryption Tools pack.
