description: Send updates on new released packs to slack channel
id: NewPacksNotifier
inputs:
- description: Comma seperated channel names on slack to send the notification to
    first workspace.
  key: channel_name
  playbookInputQuery:
  required: true
  value: {}
- description: Comma seperated channel names on slack to send the notification to
    second workspace.
  key: channel_name_second_workspace
  playbookInputQuery:
  required: false
  value: {}
name: NewPacksNotifier
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8ef691bc-ed76-4a6c-8ada-f5f3dd9cf7b7
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 8ef691bc-ed76-4a6c-8ada-f5f3dd9cf7b7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      entry_id:
        simple: ${File.EntryID}
      last_message_time_str:
        simple: ${LastRun}
      last_run_str:
        simple: ${LastRun}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Extract the index and gets a list of all new packs since last run
        into context.
      id: 267b5411-f34d-4f85-8657-793019299b78
      iscommand: false
      name: Build Slack Blocks From Index
      script: BuildSlackBlocksFromIndex
      type: regular
      version: -1
    taskid: 267b5411-f34d-4f85-8657-793019299b78
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${Blocks}
          operator: isNotEqualString
          right:
            value:
              simple: no new packs
      label: "yes"
    id: "3"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if slack blocks is not "no new packs"
      id: aea1e181-b761-4b2e-81d7-3c32d0acbd31
      iscommand: false
      name: Check If Blocks Exists
      type: condition
      version: -1
    taskid: aea1e181-b761-4b2e-81d7-3c32d0acbd31
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      listData:
        simple: ${LastRun.[1]}
      listName:
        simple: NewPacksNotifierLastRun
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.set
      id: 18ef4a8a-b589-4674-88b5-db4902f6f72d
      iscommand: true
      name: Set Last Run
      script: Builtin|||setList
      type: regular
      version: -1
    taskid: 18ef4a8a-b589-4674-88b5-db4902f6f72d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: LastRun=.
      listName:
        simple: NewPacksNotifierLastRun
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.get
      id: 854ed2ab-45a5-455d-876e-1e24462d30cc
      iscommand: true
      name: Get Last Run
      script: Builtin|||getList
      type: regular
      version: -1
    taskid: 854ed2ab-45a5-455d-876e-1e24462d30cc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9c75bf7c-eb8f-478e-8d75-135b3ce91db6
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 9c75bf7c-eb8f-478e-8d75-135b3ce91db6
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "9"
      "YES":
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      listName:
        simple: NewPacksNotifierLastRun
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if list exist in demisto lists.
      id: 916140c7-e197-412e-8e21-79f440e165b2
      iscommand: false
      name: Check If NewPacksNotifierLastRun List Exists
      script: IsListExist
      type: condition
      version: -1
    taskid: 916140c7-e197-412e-8e21-79f440e165b2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      dateFormat:
        simple: iso
      daysAgo:
        simple: "7"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Retrieves the current date and time.
      id: 75470f76-3013-4eb3-841f-0308fca55616
      iscommand: false
      name: Get Week Ago Time
      script: GetTime
      type: regular
      version: -1
    taskid: 75470f76-3013-4eb3-841f-0308fca55616
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      listData:
        simple: ${TimeNow}
      listName:
        simple: NewPacksNotifierLastRun
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.create
      id: 09b73ac8-011a-4731-870b-3e25197d8389
      iscommand: true
      name: Create NewPacksNotifierLastRun List
      script: Builtin|||createList
      type: regular
      version: -1
    taskid: 09b73ac8-011a-4731-870b-3e25197d8389
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      closeReason:
        simple: Done
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 909ce04a-4fa1-49c2-89c8-4f7e56fb863d
      iscommand: true
      name: Close Incident
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 909ce04a-4fa1-49c2-89c8-4f7e56fb863d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      method:
        simple: GET
      saveAsFile:
        simple: "yes"
      url:
        simple: https://storage.googleapis.com/marketplace-dist/content/packs/index.zip
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends http request. Returns the response as json.
      id: 4f165f68-094e-489a-8eb7-0eb662bf517d
      iscommand: false
      name: Download index.zip from marketplace-dist bucket
      script: http
      type: regular
      version: -1
    taskid: 4f165f68-094e-489a-8eb7-0eb662bf517d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      arrayData:
        simple: ${inputs.channel_name}
      contextKey:
        simple: channels
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Will create an array object in context from given string input '
      id: 32e5ca8f-3a79-48a7-8761-c1452cebd098
      iscommand: false
      name: Split Channels First Workspace
      script: CreateArray
      type: regular
      version: -1
    taskid: 32e5ca8f-3a79-48a7-8761-c1452cebd098
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1420
        }
      }
  "14":
    id: "14"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      blocks:
        simple: ${Blocks}
      channel:
        simple: ${channels}
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV3
      description: Sends a message to a user, group, or channel.
      id: 468491ca-0162-426c-8bb1-7069a2efd36a
      iscommand: true
      name: Send Slack Message to First Workspace
      script: SlackV3|||send-notification
      type: regular
      version: -1
    taskid: 468491ca-0162-426c-8bb1-7069a2efd36a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1595
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      arrayData:
        simple: ${inputs.channel_name_second_workspace}
      contextKey:
        simple: channels_second_workspace
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Will create an array object in context from given string input '
      id: 2b87865a-e2ba-4dbe-85ac-f5c64f8583ab
      iscommand: false
      name: Split Channels Second Workspace
      script: CreateArray
      type: regular
      version: -1
    taskid: 2b87865a-e2ba-4dbe-85ac-f5c64f8583ab
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1770
        }
      }
  "16":
    id: "16"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      blocks:
        simple: ${Blocks}
      channel:
        simple: ${channels_second_workspace}
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV3
      description: Sends a message to a user, group, or channel.
      id: 901ac7dd-cbb6-4d3e-8c08-9b41f1517a9b
      iscommand: true
      name: Send Slack Message to Second Workspace
      script: SlackV3|||send-notification
      type: regular
      version: -1
    taskid: 901ac7dd-cbb6-4d3e-8c08-9b41f1517a9b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1945
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2485,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
fromversion: 6.0.0
tests:
- No tests (auto formatted)
